# Generated by Django 4.2.7 on 2023-11-17 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(max_length=1000)),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        default="Deleted User",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="author_blogs",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=20)),
                (
                    "blog",
                    models.ManyToManyField(related_name="blogs_tags", to="blog.blog"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("commented_on", models.DateTimeField(auto_now_add=True)),
                ("content", models.CharField(max_length=255)),
                (
                    "blog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_comments",
                        to="blog.blog",
                    ),
                ),
                (
                    "commented_by",
                    models.ForeignKey(
                        default="Deleted User",
                        null=True,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_name="user_comments",
                        to="authentication.userprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
